### ISSUE TITLE
.NET Framework Target

### ISSUE THREAD

**Issue by jakoss** [AkkaNetContrib/Akka.Serialization.MessagePack#21]
Hey, 

I'm trying to use MessagePack on akka.net application targeting .NET Framework 4.6.1. I don't have an option to switch to core. Also - i'm using Visual Studio 2015 (and probably will for some time). 

I have this error:
![Error](https://i.imgur.com/PISm5SP.png)

Can you help me with this one? Is there an option to add Target Framework in NuGet package?

**Comment by alexvaluyskiy** [comment]
@Nekromancer `Akka.Serialization.MessagePack` targets `netstandard1.6` and should work fine with the Nuget 3.5 on Visual Studio 2015. But you have to update your VS 2015 to the latest version - Update 3

**Comment by jakoss** [comment]
Ok, i needed to update Nuget to v3.6 and install pack under `https://aka.ms/netstandard-build-support-netfx` (adds .net standard support in vs2015) and now it's working fine. Thanks
